# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a19cba77f3eaf953f9573eafff4e00121218a1d35356d77f0ab25bceacea6a03472a2e5bd735e2779e15d86274bd265856ad1e54ca736c9305a1c68333d1ac18

test:
  secret_key_base: 94932ab83ce51ef7af36fea50d82916e9642be68a226e52aee7fbfb6405c09bf48930265cdc767615ba32cb0807d4e51cb674eb9945574643465345f2fe8143e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
